[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_RECAPTCHA_SITE_KEY"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
